#Controller to control robot arm joints
fanuc_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [Joint_1, Joint_2, Joint_3, Joint_4, Joint_5, Joint_6]
  
#Controller to control end effector joints
ee_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [robotiq_140_left_knuckle_joint]
  
#Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
