controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
      - Joint_6
  - name: fake_gripper_group_controller
    type: $(arg fake_execution_type)
    joints:
      - robotiq_140_left_knuckle_joint
initial:  # Define initial robot poses per group
  - group: arm_group
    pose: home
  - group: gripper_group
    pose: gripper_open